const createResearchPaperDB = `
    CREATE TABLE IF NOT EXISTS research_Papers(
      paper_id INT PRIMARY KEY AUTO_INCREMENT,
      paper_title VARCHAR(50),conference TEXT,
      publish_date DATE
    );`;
const addForeignKeyToResearchPaper = `
 ALTER TABLE research_Papers ADD fk_author_no INT`;
const addAuthorForeignKeyToResearch = `
ALTER TABLE research_Papers 
ADD FOREIGN KEY (fk_author_no) REFERENCES author(author_no);`;
const insertIntoAuthor = [
  {
    author_no: 1,
    author_name: 'Wouter',
    university: 'MIT',
    date_of_birth: '1967-01-01',
    h_index: 4,
    gender: 'm',
    mentor: 1,
  },
  {
    author_no: 2,
    author_name: 'Jane',
    university: 'Cambridge',
    date_of_birth: '1977-01-01',
    h_index: 5,
    gender: 'f',
    mentor: 2,
  },
  {
    author_no: 3,
    author_name: 'Lydia',
    university: 'Groningen',
    date_of_birth: '1985-03-01',
    h_index: 6,
    gender: 'f',
    mentor: 1,
  },
  {
    author_no: 4,
    author_name: 'Claudia',
    university: 'Amsterdam',
    date_of_birth: '1987-06-01',
    h_index: 5,
    gender: 'f',
    mentor: 1,
  },
  {
    author_no: 5,
    author_name: 'Obada',
    university: 'El-Ehzer',
    date_of_birth: '1988-07-11',
    h_index: 7,
    gender: 'm',
    mentor: 1,
  },
  {
    author_no: 6,
    author_name: 'Fikret',
    university: 'Maastricht',
    date_of_birth: '1990-07-11',
    h_index: 4,
    gender: 'm',
    mentor: 5,
  },
  {
    author_no: 7,
    author_name: 'Esranur',
    university: 'Oxford',
    date_of_birth: '1988-09-11',
    h_index: 4,
    gender: 'f',
    mentor: 5,
  },
  {
    author_no: 8,
    author_name: 'Amar',
    university: 'El-Ehzer',
    date_of_birth: '1990-07-11',
    h_index: 3,
    gender: 'm',
    mentor: 2,
  },
  {
    author_no: 9,
    author_name: 'Bachar',
    university: 'Mexico',
    date_of_birth: '1984-08-11',
    h_index: 7,
    gender: 'm',
    mentor: 1,
  },
  {
    author_no: 10,
    author_name: 'Mustafa',
    university: 'Amsterdam',
    date_of_birth: '1992-09-11',
    h_index: 4,
    gender: 'm',
    mentor: 1,
  },
  {
    author_no: 28,
    author_name: 'Emine',
    university: 'Malatya',
    date_of_birth: '1992-01-11',
    h_index: 5,
    gender: 'f',
    mentor: 5,
  },
  {
    author_no: 12,
    author_name: 'Sadek',
    university: 'Utrecht',
    date_of_birth: '1988-02-22',
    h_index: 3,
    gender: 'm',
    mentor: 1,
  },
  {
    author_no: 13,
    author_name: 'Reshadi',
    university: 'Cambridge',
    date_of_birth: '1988-04-21',
    h_index: 6,
    gender: 'm',
    mentor: 5,
  },
  {
    author_no: 14,
    author_name: 'George',
    university: 'Amsterdam',
    date_of_birth: '1989-07-11',
    h_index: 5,
    gender: 'm',
    mentor: 7,
  },
  {
    author_no: 15,
    author_name: 'Marsel',
    university: 'MIT',
    date_of_birth: '1978-07-11',
    h_index: 8,
    gender: 'm',
    mentor: 3,
  },
  {
    author_no: 16,
    author_name: 'Antonio',
    university: 'Mexico',
    date_of_birth: '1984-03-11',
    h_index: 7,
    gender: 'm',
    mentor: 4,
  },
];
const insertResearchPapers = [
  {
    paper_id: 11,
    paper_title: 'Javascript',
    conference: 'Central Academy',
    publish_date: '2000-01-01',
    fk_author_no: 1,
  },
  {
    paper_id: 12,
    paper_title: 'Node JS',
    conference: 'HYF Academy',
    publish_date: '2000-02-01',
    fk_author_no: 8,
  },
  {
    paper_id: 13,
    paper_title: 'Javascript',
    conference: 'HYF Academy',
    publish_date: '2000-03-01',
    fk_author_no: 2,
  },
  {
    paper_id: 14,
    paper_title: 'Angular JS',
    conference: 'Cambridge Academy',
    publish_date: '2000-04-01',
    fk_author_no: 2,
  },
  {
    paper_id: 15,
    paper_title: 'Vue JS',
    conference: 'HYF Academy',
    publish_date: '2002-02-01',
    fk_author_no: 3,
  },
  {
    paper_id: 16,
    paper_title: 'Node JS',
    conference: 'HYF Academy',
    publish_date: '2000-02-01',
    fk_author_no: 3,
  },
  {
    paper_id: 17,
    paper_title: 'React JS',
    conference: 'MIT Academy',
    publish_date: '1995-02-01',
    fk_author_no: 1,
  },
  {
    paper_id: 18,
    paper_title: 'HTML',
    conference: 'HYF Academy',
    publish_date: '2000-02-01',
    fk_author_no: 7,
  },
  {
    paper_id: 19,
    paper_title: 'HTML',
    conference: 'Cambridge Academy',
    publish_date: '2000-08-01',
    fk_author_no: 6,
  },
  {
    paper_id: 20,
    paper_title: 'CSS',
    conference: 'EL-Ehzer Academy',
    publish_date: '2002-02-01',
    fk_author_no: 6,
  },
  {
    paper_id: 21,
    paper_title: 'Tailwind',
    conference: 'HYF Academy',
    publish_date: '2005-02-01',
    fk_author_no: 1,
  },
  {
    paper_id: 22,
    paper_title: 'Bootstrap 4.1',
    conference: 'Inonu Academy',
    publish_date: '2004-02-01',
    fk_author_no: 13,
  },
  {
    paper_id: 23,
    paper_title: 'Node JS',
    conference: 'Amsterdam Academy',
    publish_date: '2006-02-01',
    fk_author_no: 1,
  },
  {
    paper_id: 24,
    paper_title: 'SQL and MYSQL',
    conference: 'Groningen Academy',
    publish_date: '2008-02-01',
    fk_author_no: 14,
  },
  {
    paper_id: 25,
    paper_title: 'Mongoose',
    conference: 'Utrecht Academy',
    publish_date: '2006-02-01',
    fk_author_no: 5,
  },
  {
    paper_id: 26,
    paper_title: 'Next JS',
    conference: 'HYF Academy',
    publish_date: '2005-02-01',
    fk_author_no: 12,
  },
  {
    paper_id: 27,
    paper_title: 'TypeScript',
    conference: 'Maastricht Academy',
    publish_date: '2008-02-01',
    fk_author_no: 3,
  },
  {
    paper_id: 28,
    paper_title: 'Angular JS',
    conference: 'Maastricht Academy',
    publish_date: '2007-02-01',
    fk_author_no: 3,
  },
  {
    paper_id: 29,
    paper_title: 'API and Browser',
    conference: 'HYF Academy',
    publish_date: '2004-02-01',
    fk_author_no: 14,
  },
  {
    paper_id: 30,
    paper_title: 'Vue JS',
    conference: 'Amsterdam Academy',
    publish_date: '2009-05-01',
    fk_author_no: 1,
  },
  {
    paper_id: 31,
    paper_title: 'React Native JS',
    conference: 'Groningen Academy',
    publish_date: '2009-09-09',
    fk_author_no: 9,
  },
  {
    paper_id: 32,
    paper_title: 'Node JS',
    conference: 'HYF Academy',
    publish_date: '2000-02-01',
    fk_author_no: 2,
  },
  {
    paper_id: 33,
    paper_title: 'GraphQL ',
    conference: 'Inonu Academy',
    publish_date: '2009-06-01',
    fk_author_no: 4,
  },
  {
    paper_id: 34,
    paper_title: 'Python',
    conference: 'Cambridge Academy',
    publish_date: '2000-12-01',
    fk_author_no: 12,
  },
  {
    paper_id: 35,
    paper_title: 'Django',
    conference: 'HYF Academy',
    publish_date: '2012-02-01',
    fk_author_no: 13,
  },
  {
    paper_id: 36,
    paper_title: 'SQLite',
    conference: 'Groningen Academy',
    publish_date: '2014-02-01',
    fk_author_no: 14,
  },
  {
    paper_id: 37,
    paper_title: 'Java',
    conference: 'HYF Academy',
    publish_date: '2012-02-01',
    fk_author_no: 4,
  },
  {
    paper_id: 38,
    paper_title: 'PHP',
    conference: 'HYF Academy',
    publish_date: '2015-02-01',
    fk_author_no: 5,
  },
  {
    paper_id: 39,
    paper_title: 'Go',
    conference: 'Inonu Academy',
    publish_date: '2019-02-01',
    fk_author_no: 9,
  },
  {
    paper_id: 40,
    paper_title: 'Typescript',
    conference: 'Oxford Academy',
    publish_date: '2004-02-01',
    fk_author_no: 14,
  },
];

module.exports.createResearchPaperDB = createResearchPaperDB;
module.exports.addForeignKeyToResearchPaper = addForeignKeyToResearchPaper;
module.exports.addAuthorForeignKeyToResearch = addAuthorForeignKeyToResearch;
module.exports.insertIntoAuthor = insertIntoAuthor;
module.exports.insertResearchPapers = insertResearchPapers;
